export const TRAER_TODAS = 'tareas_traer_todas'
export const CARGANDO = 'tareas_cargando'
export const ERROR = 'tareas_error'
export const CAMBIO_USUARIO = 'cambio_usuario_id'
export const CAMBIO_TITULO = 'cambio_titulo'
export const GUARDAR = 'tareas_agregada'
export const ACTUALIZAR = 'tareas_actualizar'
export const LIMPIAR = 'tareas_limpiar_forma'